sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    access-key-id: LTAI5tEZQQGhiCyAgBGKB8C2
    access-key-secret: y4XDvrnfQfQUcIAPWU1H7qy4FUGWmN
    bucket-name: web-tlias-guclassmate

  redis:
    host: localhost
    port: 6379
    password:
    database: 10
  wechat:
    appid: wxed585933df1aec4e
    secret: 66c54f64c58564649e15efd0e1be4c7a